# Generated by Django 3.2.6 on 2021-08-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanglaWords',
            fields=[
                ('bng_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('bangla_word', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Bangla Words',
            },
        ),
        migrations.CreateModel(
            name='EnglishWords',
            fields=[
                ('eng_id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'English Words',
            },
        ),
        migrations.CreateModel(
            name='BanglaEnglishRelations',
            fields=[
                ('bng_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wordnet.banglawords')),
            ],
            options={
                'verbose_name_plural': 'Bangla English Relations',
            },
        ),
        migrations.CreateModel(
            name='Senses',
            fields=[
                ('sense_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('synset', models.CharField(max_length=32)),
                ('eng_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordnet.englishwords')),
            ],
            options={
                'verbose_name_plural': 'Senses',
            },
        ),
        migrations.AddField(
            model_name='englishwords',
            name='bangla_word',
            field=models.ManyToManyField(through='wordnet.BanglaEnglishRelations', to='wordnet.BanglaWords'),
        ),
        migrations.AddField(
            model_name='banglaenglishrelations',
            name='eng_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordnet.englishwords'),
        ),
    ]
